defaults:
  - _self_

name: fno

dim: 3d # options: 2d, 3d
loss: H1
lr: 0.001
weight_decay: 0.001
n_modes_space: 16
n_modes_time: 16 # only 3d
hidden_channels: 32
in_channels: 3
out_channels: 3
lifting_channels: 16
projection_channels: 16
n_layers: 6
