defaults:
  - _self_

name: lran

ae_ckpt: ${paths.model_dir}/3d_ae/ld/ra${data.ra}.ckpt
input_size: [4, 48, 32, 48]
latent_dimension: 1024
lambda_id: 1
lambda_fwd: 1
lambda_hid: 100
lr_operator: 0.0001
lr_autoencoder: 0.003
train_autoencoder: true
